language: python
cache: pip
env: OMP_NUM_THREADS=2
jobs:
  include:
    - name: "amd64"
      arch: amd64
    - name: "arm64"
      arch: arm64
    - name: "macOS"
      os: osx
      osx_image: xcode11.2
      language: shell
    - name: "Windows"
      os: windows
      language: shell
      before_install:
        - choco install python
        - python -m pip install -U pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
      install:
        - python -V
        - pip -V
        - pip install -U pip
        - pip install -Ur requirements.txt
        - USE_VC=1 python setup.py build_ext -i
      script:
        - python travis.py
        - python setup.py build_sphinx
    - name: "gpu"
      arch: amd64
      dist: focal
      install:
        - sudo apt-get update
        - sudo apt-get install ocl-icd-opencl-dev intel-opencl-icd clinfo
        - USE_GPU=1 python3 setup.py build_ext -i
      script:
        - clinfo
before_install:
  - python3 -V
  - pip3 -V
  - pip3 install -U pip
  - pip3 install -Ur requirements.txt
install:
  - python3 setup.py build_ext -i
script:
  - python3 travis.py
  - python3 setup.py build_sphinx

