language: python
cache: pip
env: OMP_NUM_THREADS=2
jobs:
  include:
    - name: "amd64"
      arch: amd64
    - name: "arm64"
      arch: arm64
    - name: "macOS"
      os: osx
      osx_image: xcode11.2
      language: shell
    - name: "Windows"
      os: windows
      language: shell
      before_install:
        - choco install python
        - pip install -U pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
      install:
        - pip install -Ur requirements.txt
        - USE_VC=1 python setup.py build_ext -i
install:
  - python -V
  - pip install -U pip
  - pip install -Ur requirements.txt
  - python setup.py build_ext -i
script:
  - python travis.py

